name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USRNAME: ${{ vars.DOCKERHUB_USERNAME }}
      PASSWORD: ${{ vars.PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build project
        run: echo $USRNAME and $PASSWORD

  test:
    runs-on: ubuntu-latest
    needs: build       # 👈 test waits for build
    steps:
      - name: Run tests
        run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: test        # 👈 deploy waits for test
    steps:
      - name: Deploy
        run: echo "Deploying..."
